Initial Code
cosmoscout/csp-gaussian-splatting pull request #1
Opened 2023-11-16 09:21 UTC by Schneegans

For testing this, you can download pre-trained models from [here](https://repo-sam.inria.fr/fungraph/3d-gaussian-splatting/datasets/pretrained/models.zip) and add something like this to your config:

```json
"csp-gaussian-splatting": {
      "radianceFields": [
        {
          "ply": "<path-to-pre-trained-dataset>\\point_cloud\\iteration_30000\\point_cloud.ply",
          "object": "Earth",
          "lnglat": [7.0, 54.0],
          "rotation": [1.0, 0.0, 0.0, 0.0],
          "scale": 500.0,
          "altitude": 1000.0
        }
      ]
    },
```

And the radiance field will show up above Helgoland!

2023-11-21 13:40 UTC, JonasGilg requested changes
There are some issues with CUDA. I suggested changes in the CMakeLists.txt to fix at least the configuration, but I also had to manually copy cudas `.lib` and `.dll` files to the install directory.

Additionally, the rendering performance is not very good. At least on my notebook, I am CPU bottlenecked with a Intel Core i9-12950HX.

2023-11-21 13:40 UTC, JonasGilg commented on CMakeLists.txt
> +find_package(CUDA 11.0 REQUIRED)
I get the following error, when running CMake:

```
CMake Warning (dev) at plugins/csp-gaussian-splatting/CMakeLists.txt:16 (find_package):
  Policy CMP0146 is not set: The FindCUDA module is removed.  Run "cmake
  --help-policy CMP0146" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.
```

Here is a more detailed description for this error: https://cmake.org/cmake/help/latest/policy/CMP0146.html

2023-11-21 13:40 UTC, JonasGilg commented on shaders/copy.frag
> +	float a = source.data[3 * width * height + (y * width + x)];
```suggestion

        int size   = width * height;
        int offset = (y * width + x);
        
	float r = source.data[0 * size + offset];
	float g = source.data[1 * size + offset];
	float b = source.data[2 * size + offset];
	float a = source.data[3 * size + offset];
```

2023-11-21 13:40 UTC, JonasGilg commented on shaders/copy.vert
> +  // No tranformation here since we draw a full screen quad.
The code above creates a full screen triangle.

```suggestion
  // No tranformation here since we draw a full screen triangle.
```

2023-11-21 13:40 UTC, JonasGilg commented on shaders/gaussian_surface.frag
> +}
```suggestion
void main(void) {
  vec3 dir = normalize(worldPos - rayOrigin);

  vec3 normal;
  vec3 intersection = closestEllipsoidIntersection(dir, normal);
  float align = max(0.4, dot(-dir, normal));

  out_color = vec4(1, 0, 0, 1);

  if (intersection == vec3(0))
    discard;

  float a = stage == 0 ? 1.0 : 0.05;

  out_color = vec4(align * colorVert, a);
}
```

2023-11-21 13:40 UTC, JonasGilg commented on shaders/gaussian_surface.vert
> +}
```suggestion
void main() {
  boxID = gl_InstanceID;
  ellipsoidCenter = vec3(centers[3 * boxID + 0], centers[3 * boxID + 1], centers[3 * boxID + 2]);
  float a = alphas[boxID];
  alphaVert = a;
  ellipsoidScale = vec3(scales[3 * boxID + 0], scales[3 * boxID + 1], scales[3 * boxID + 2]);
  ellipsoidScale = 2 * ellipsoidScale;

  vec4 q = rots[boxID];
  ellipsoidRotation = transpose(quatToMat3(q));

  int vertexIndex = boxIndices[gl_VertexID];
  worldPos = ellipsoidRotation * (ellipsoidScale * boxVertices[vertexIndex]);
  worldPos += ellipsoidCenter;

  float r = colors[boxID * 48 + 0] * 0.2 + 0.5;
  float g = colors[boxID * 48 + 1] * 0.2 + 0.5;
  float b = colors[boxID * 48 + 2] * 0.2 + 0.5;

  colorVert = vec3(r, g, b);

  if ((stage == 0 && a < alpha_limit) || (stage == 1 && a >= alpha_limit))
    gl_Position = vec4(0, 0, 0, 0);
  else
    gl_Position = MVP * vec4(worldPos, 1);
}
```

2023-11-21 13:40 UTC, JonasGilg commented on src/GaussianRenderer.cpp
> +  return 1.0f / (1.0f + exp(-m1));
```suggestion
  return 1.0f / (1.0f + std::exp(-m1));
```

2023-11-21 13:40 UTC, JonasGilg commented on src/GaussianRenderer.cpp
> +    if (buff.compare("end_header") == 0) {
```suggestion
    if (buff == "end_header") {
```

2023-11-21 13:40 UTC, JonasGilg commented on src/GaussianRenderer.cpp
> +  infile.read((char*)points.data(), count * sizeof(GaussianData::RichPoint<D>));
```suggestion
  infile.read(reinterpret_cast<char*>(points.data()), count * sizeof(GaussianData::RichPoint<D>));
```

2023-11-21 13:40 UTC, JonasGilg commented on src/GaussianRenderer.cpp
> +  minn = Vector3f(FLT_MAX, FLT_MAX, FLT_MAX);
We shouldn't use the C standard library.

```suggestion
  minn = Vector3f(std::numeric_limits<float>::max(), std::numeric_limits<float>::max(),
      std::numeric_limits<float>::max());
```

2023-11-21 13:40 UTC, JonasGilg commented on src/GaussianRenderer.cpp
> +    Vector3f scaled = ((float((1 << 21) - 1)) * rel);
```suggestion
    Vector3f scaled = static_cast<float>((1 << 21) - 1) * rel;
```

2023-11-21 13:40 UTC, JonasGilg commented on src/GaussianRenderer.cpp
> +  }
Both loops use `i` as the loop index name.

2023-11-21 13:40 UTC, JonasGilg commented on src/GaussianRenderer.cpp
> +      code |= ((uint64_t(xyz.z() & (1 << i))) << (2 * i + 2));
```suggestion
      code |= static_cast<uint64_t>(xyz.x() & (1 << i)) << (2 * i + 0);
      code |= static_cast<uint64_t>(xyz.y() & (1 << i)) << (2 * i + 1);
      code |= static_cast<uint64_t>(xyz.z() & (1 << i)) << (2 * i + 2);
```

2023-11-21 13:40 UTC, JonasGilg commented on src/GaussianRenderer.cpp
> +  cs::utils::FrameStats::ScopedTimer timer("Gaussian Renderer for " + mRadianceField.mPLY);
If a windows path is provided for the ply with backslashes (like `C:\Users\xyz\...`), this will lead to errors in the FrameStats.

2023-11-21 13:40 UTC, JonasGilg commented on src/GaussianRenderer.cpp
> +  // Compute ENO (east-north-up) rotation for the given location on the planet.
```suggestion
  // Compute ENU (east-north-up) rotation for the given location on the planet.
```

2023-11-21 13:40 UTC, JonasGilg commented on src/renderer/GaussianData.cpp
> +      cudaMemcpy(mScaleCuda, scale.data(), sizeof(Scale) * count, cudaMemcpyHostToDevice));
```suggestion
  // Allocate and fill the GPU data
  CUDA_SAFE_CALL_ALWAYS(cudaMalloc(reinterpret_cast<void**>(&mPosCuda), sizeof(Pos) * count));
  CUDA_SAFE_CALL_ALWAYS(
      cudaMemcpy(mPosCuda, pos.data(), sizeof(Pos) * count, cudaMemcpyHostToDevice));
  CUDA_SAFE_CALL_ALWAYS(cudaMalloc(reinterpret_cast<void**>(&mRotCuda), sizeof(Rot) * count));
  CUDA_SAFE_CALL_ALWAYS(
      cudaMemcpy(mRotCuda, rot.data(), sizeof(Rot) * count, cudaMemcpyHostToDevice));
  CUDA_SAFE_CALL_ALWAYS(cudaMalloc(reinterpret_cast<void**>(&mShsCuda), sizeof(SHs<3>) * count));
  CUDA_SAFE_CALL_ALWAYS(
      cudaMemcpy(mShsCuda, color.data(), sizeof(SHs<3>) * count, cudaMemcpyHostToDevice));
  CUDA_SAFE_CALL_ALWAYS(cudaMalloc(reinterpret_cast<void**>(&mOpacityCuda), sizeof(float) * count));
  CUDA_SAFE_CALL_ALWAYS(
      cudaMemcpy(mOpacityCuda, alpha.data(), sizeof(float) * count, cudaMemcpyHostToDevice));
  CUDA_SAFE_CALL_ALWAYS(cudaMalloc(reinterpret_cast<void**>(&mScaleCuda), sizeof(Scale) * count));
  CUDA_SAFE_CALL_ALWAYS(
      cudaMemcpy(mScaleCuda, scale.data(), sizeof(Scale) * count, cudaMemcpyHostToDevice));
```

2023-11-21 13:40 UTC, JonasGilg commented on src/renderer/GaussianData.cpp
> +  glNamedBufferStorage(mColorOpenGL, count * sizeof(float) * 48, &color[0], 0);
```suggestion
  glNamedBufferStorage(mPosOpenGL, count * 3 * sizeof(float), pos.data(), 0);
  glNamedBufferStorage(mRotOpenGL, count * 4 * sizeof(float), rot.data(), 0);
  glNamedBufferStorage(mScaleOpenGL, count * 3 * sizeof(float), scale.data(), 0);
  glNamedBufferStorage(mAlphaOpenGL, count * sizeof(float), alpha.data(), 0);
  glNamedBufferStorage(mColorOpenGL, count * sizeof(float) * 48, color.data(), 0);
```

2023-11-21 13:40 UTC, JonasGilg commented on src/renderer/GaussianData.hpp
> +    float shs[(D + 1) * (D + 1) * 3];
```suggestion
    std::array<float, (D + 1) * (D + 1) * 3> shs;
```

2023-11-21 13:40 UTC, JonasGilg commented on src/renderer/GaussianData.hpp
> +    float scale[3];
```suggestion
    std::array<float, 3> scale;
```

2023-11-21 13:40 UTC, JonasGilg commented on src/renderer/GaussianData.hpp
> +    float rot[4];
```suggestion
    std::array<float, 4> rot;
```

2023-11-21 13:40 UTC, JonasGilg commented on src/renderer/GaussianData.hpp
> +    Rot    rot;
```suggestion
    Pos                  pos;
    std::array<float, 3> n;
    SHs<D>               shs;
    float                opacity;
    Scale                scale;
    Rot                  rot;
```

2023-11-21 13:40 UTC, JonasGilg commented on src/renderer/SplatRenderer.cpp
> +  CUDA_SAFE_CALL_ALWAYS(cudaMalloc((void**)&mBackgroundCuda, 3 * sizeof(float)));
```suggestion
  CUDA_SAFE_CALL_ALWAYS(cudaMalloc(reinterpret_cast<void**>(&mViewCuda), sizeof(Matrix4f)));
  CUDA_SAFE_CALL_ALWAYS(cudaMalloc(reinterpret_cast<void**>(&mProjCuda), sizeof(Matrix4f)));
  CUDA_SAFE_CALL_ALWAYS(cudaMalloc(reinterpret_cast<void**>(&mCamPosCuda), 3 * sizeof(float)));
  CUDA_SAFE_CALL_ALWAYS(cudaMalloc(reinterpret_cast<void**>(&mBackgroundCuda), 3 * sizeof(float)));
```

2023-11-21 13:40 UTC, JonasGilg commented on src/renderer/SplatRenderer.cpp
> +      return reinterpret_cast<char*>(*ptr);
```suggestion
      return static_cast<char*>(*ptr);
```

2023-11-21 13:40 UTC, JonasGilg commented on src/logger.hpp
> +/// This creates the default singleton logger for "csp-gaussiansplatting" when called for the first
```suggestion
/// This creates the default singleton logger for "csp-gaussian-splatting" when called for the first
```

2023-11-21 13:40 UTC, JonasGilg commented on src/renderer/SplatRenderer.cpp
> +  mUniforms.mHeight = glGetUniformLocation(mCopyShader.GetProgram(), "height");
```suggestion

  mUniforms.mWidth  = mCopyShader.GetUniformLocation("width");
  mUniforms.mHeight = mCopyShader.GetUniformLocation("height");
```

2023-11-21 13:40 UTC, JonasGilg commented on src/renderer/SplatRenderer.cpp
> +  }
```suggestion
  for (auto const& [viewport, data] : mViewportData) {
    if (!data.mInteropFailed) {
      cudaGraphicsUnregisterResource(data.mImageBufferCuda);
    } else {
      cudaFree(data.mFallbackBufferCuda);
    }
    glDeleteBuffers(1, &data.mImageBuffer);
  }
```

2023-11-21 13:40 UTC, JonasGilg commented on src/renderer/SplatRenderer.cpp
> +        (void**)&image_cuda, &bytes, viewportData.mImageBufferCuda));
```suggestion
    CUDA_SAFE_CALL(cudaGraphicsResourceGetMappedPointer(
        reinterpret_cast<void**>(&image_cuda), &bytes, viewportData.mImageBufferCuda));
```

2023-11-21 13:40 UTC, JonasGilg commented on src/renderer/SplatRenderer.cpp
> +    }
`useInterop` is always true here.

```suggestion
    if (cudaPeekAtLastError() != cudaSuccess) {
      logger().error(
          "A CUDA error occurred in setup: {}", cudaGetErrorString(cudaGetLastError()));
    }
    cudaGraphicsGLRegisterBuffer(
        &data.mImageBufferCuda, data.mImageBuffer, cudaGraphicsRegisterFlagsWriteDiscard);
    useInterop &= (cudaGetLastError() == cudaSuccess);
```

2023-11-21 13:40 UTC, JonasGilg commented on src/renderer/SplatRenderer.hpp
> +  std::function<char*(size_t N)> mGeomBufferFunc, mBinningBufferFunc, mImgBufferFunc;
```suggestion
  size_t mAllocdGeom    = 0;
  size_t mAllocdBinning = 0;
  size_t mAllocdImg     = 0;

  void* mGeomPtr    = nullptr;
  void* mBinningPtr = nullptr;
  void* mImgPtr     = nullptr;

  std::function<char*(size_t N)> mGeomBufferFunc;
  std::function<char*(size_t N)> mBinningBufferFunc;
  std::function<char*(size_t N)> mImgBufferFunc;
```

2023-11-21 13:40 UTC, JonasGilg commented on src/renderer/SurfaceRenderer.cpp
> +  mUniforms.mParamStage  = glGetUniformLocation(mShader.GetProgram(), "stage");
```suggestion
  mUniforms.mParamCamPos = mShader.GetUniformLocation("rayOrigin");
  mUniforms.mParamMVP    = mShader.GetUniformLocation("MVP");
  mUniforms.mParamLimit  = mShader.GetUniformLocation("alpha_limit");
  mUniforms.mParamStage  = mShader.GetUniformLocation("stage");
```

2023-11-21 13:40 UTC, JonasGilg commented on src/renderer/SplatRenderer.cpp
> +  glDrawArrays(GL_TRIANGLE_STRIP, 0, 4);
In the vertex shader a full screen triangle is created.

```suggestion
  glDrawArrays(GL_TRIANGLE_STRIP, 0, 3);
```

2023-11-21 13:40 UTC, JonasGilg commented on CMakeLists.txt
> +find_package(CUDA 11.0 REQUIRED)
```suggestion
enable_language(CUDA)
find_package(CUDAToolkit REQUIRED)
```

2023-11-21 13:40 UTC, JonasGilg commented on CMakeLists.txt
> +target_include_directories(csp-gaussian-splatting PUBLIC ${CUDA_INCLUDE_DIRS})
```suggestion
target_link_libraries(csp-gaussian-splatting
  PUBLIC
    cs-core
    CudaRasterizer
    CUDA::cudart
    CUDA::cuda_driver
)
```

2023-11-21 16:58 UTC, Schneegans commented
Hi there! Thanks for the review. A lot of the things you mentioned are inherited from the original code from [here](https://gitlab.inria.fr/sibr/sibr_core/-/tree/fossa_compatibility/src/projects/gaussianviewer/renderer). We could improve them, but 90% of the changes would be cosmetic / code style and / or according to best practices. So I am not sure, whether we should apply them here, as this will make incorporation of upstream changes in the future harder. What do you think?

2023-11-22 11:04 UTC, JonasGilg commented
> Hi there! Thanks for the review. A lot of the things you mentioned are inherited from the original code from [here](https://gitlab.inria.fr/sibr/sibr_core/-/tree/fossa_compatibility/src/projects/gaussianviewer/renderer). We could improve them, but 90% of the changes would be cosmetic / code style and / or according to best practices. So I am not sure, whether we should apply them here, as this will make incorporation of upstream changes in the future harder. What do you think?

Hmm, it would at least be practical then, to exclude these files from code analysis tools ... On the other hand, you already modified and restructured a lot of the original code.

I would make it you call, which suggestion you take over and which you would leave as is.

2023-11-28 10:16 UTC, JonasGilg approved these changes

2023-11-28 11:27 UTC, merged